global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # Scrape Prometheus server
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Scrape Node Exporter
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  # Scrape cAdvisor (monitor Docker containers)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'fastapi_app'
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]